import './globals.css';
import { Nova_Mono } from 'next/font/google';


const roboto = Nova_Mono({ 
  subsets: ['latin'],
  weight: '400',
  variable: '--font-roboto'
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={`${roboto.variable}`}>{children}</body>
    </html>
  )
}
